### ISSUE TITLE
JP2 IsValidJP2 False

### ISSUE THREAD

**Issue by renarios** [bitsgalore/jpylyzer#3]
I received a few thousand JPEG2000 files from a bulk scan. I tried to validate them by using jpylyzer. On a few hundred files I got the isValidJP2 "False", but when I checked them subsequently with jhove, I got the message "Valid and Well-formed". I can open them in a viewer (on Windows, not on Linux :-/)  Now I don't know if they're valid or not. I uploaded the jp2 and jpjylyzer output.
[jpylyzer.log](https://github.com/bitsgalore/jpylyzer/files/2608696/jpylyzer.log)
[1979_08_20_02_030.jp2.zip](https://github.com/bitsgalore/jpylyzer/files/2608706/1979_08_20_02_030.jp2.zip)

Can you guys help me out?

**Comment by bitsgalore** [comment]
The reason for the jpylyzer validation errors is that your image is actually not a JP2 (JPEG 2000 Part 1), but a JPX (JPEG 2000 Part 2) file. You can see this from the `colourSpecification` box, which uses the `AnyICC` method, which is not allowed in JP2 (but it is allowed in JPX). Most JP2 readers are able to read/display images like this one, but a JP2-only compliant reader will not be able to interpret the embedded ICC profile correctly. See also:

<http://wiki.opf-labs.org/display/TR/Handling+of+ICC+profiles>

Incidentally, most format identification tools (DROID, Unix File, etc.) will identify these files as JP2 (not JPX!), which happens because Adobe Photoshop (which is the writer application) writes a wrong `brand` value to the fileTypeBox. This is a known issue: 

<http://wiki.opf-labs.org/display/TR/Files+identified+as+JP2+are+really+JPX>

JHOVE's JP2 validation is less thorough than jpylyzer, which is why JHOVE doesn't detect this particular issue.

So the short answer to your question is that this is *not* a valid JP2 (and it's not a valid JPX either).

**Comment by renarios** [comment]
Thanks for the quick answer. Guess I have some more reading to do ;-)
